language: python
os: linux

jobs:
  fast_finish: true
  include:
    - env:
      - PYTHON=2.7
      - COVERAGE='false'
      - DOCS='True'

script:
    - if [[ $DOCS == 'true' ]]; then source ci/build_docs.sh; fi

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        condition: $DOCS = 'true'
